# shellcheck shell=bash
# systemd — PID 1, udev, logind, and systemd-boot.
#
# The largest and most opinionated recipe in the tree. systemd has roughly forty
# optional dependencies, and the default answer to each is "yes, if found",
# which for a cross build means "silently differs depending on what happens to
# be installed in the container". So every one is answered explicitly below.
#
# The guiding rule: an immutable, image-based distribution with a C# desktop on
# top needs PID 1, udev, journald, logind and systemd-boot. It does not need
# systemd's networking, DNS, home directory, or container management, and each
# of those declined here is a dependency not built and an attack surface not
# shipped. They can be enabled later when something actually wants them.

RECIPE_SOURCE="systemd"
RECIPE_DEPENDS="glibc-runtime llvm-runtime util-linux libcap kmod libxcrypt zlib xz zstd"

# systemd carries its own copies of a few dozen kernel UAPI headers under
# src/basic/linux/, so that it builds against a newer kernel's interfaces than
# whatever headers the build host happens to have. That assumption inverts
# here: Trinix builds the kernel it ships, so the sysroot's headers are by
# definition the newest and the vendored copies are the stale ones.
#
# The two input headers are where that inversion actually bites. udev's table
# of key names is generated by preprocessing <linux/input.h> *without* the
# source tree's include paths, so the generator reads the sysroot's 6.12
# header, while udev-builtin-keyboard.c compiles with -Isrc/basic and reads the
# vendored one. Any key code present in the first and missing from the second —
# KEY_LINK_PHONE, at the time of writing — becomes an undeclared identifier in
# generated code, which is a memorable way to spend an afternoon.
#
# Deleting the two copies makes both sides read the sysroot, which is the
# coherent answer rather than a workaround: there is exactly one kernel here
# and its headers are the ones in the sysroot.
trinix_patch() {
    rm -f "$SRCDIR/src/basic/linux/input.h" \
          "$SRCDIR/src/basic/linux/input-event-codes.h"
}

trinix_build() {
    # systemd's meson build runs target helper programs during configure to
    # probe behaviour; the cross file wires qemu-user in as exe_wrapper so those
    # probes work rather than being guessed.
    meson setup "$BUILDDIR" "$SRCDIR" \
        --cross-file "$MESON_CROSS" \
        --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --buildtype=release \
        -Dmode=release \
        \
        `# --- What Trinix actually uses -----------------------------------` \
        -Dkmod=enabled \
        -Dblkid=enabled \
        -Dzlib=enabled \
        -Dxz=enabled \
        -Dzstd=enabled \
        -Dbootloader=enabled \
        \
        `# --- Declined: security frameworks the base image does not have ---` \
        -Dselinux=disabled \
        -Dapparmor=disabled \
        -Dsmack=false \
        -Dima=false \
        -Daudit=disabled \
        -Dseccomp=disabled \
        -Dpam=disabled \
        -Dpolkit=disabled \
        \
        `# --- Declined: crypto and TLS stacks not yet in the base ----------` \
        -Dopenssl=disabled \
        -Dgcrypt=disabled \
        -Dp11kit=disabled \
        -Dlibcryptsetup=disabled \
        -Dtpm=false \
        -Dtpm2=disabled \
        -Dlibfido2=disabled \
        \
        `# --- Declined: subsystems Trinix replaces or does not want --------` \
        -Dnetworkd=false \
        -Dresolve=false \
        -Dhomed=disabled \
        -Duserdb=false \
        -Dportabled=false \
        -Dsysupdate=disabled \
        -Dmachined=false \
        `# systemd-nspawn has no build option in 257; it comes along` \
        `# with the base build and is simply never installed as a unit.` \
        -Dimportd=disabled \
        -Doomd=false \
        -Dremote=disabled \
        -Dcoredump=false \
        -Dpstore=false \
        -Dhwdb=false \
        -Dlocaled=false \
        -Dtimesyncd=false \
        -Dfirstboot=false \
        -Dvconsole=false \
        -Dquotacheck=false \
        -Drandomseed=false \
        -Dbacklight=false \
        -Drfkill=false \
        -Dhibernate=false \
        -Dinitrd=true \
        \
        `# --- Declined: optional libraries --------------------------------` \
        -Dlibcurl=disabled \
        -Dlibidn=disabled \
        -Dlibidn2=disabled \
        -Dlibiptc=disabled \
        -Dmicrohttpd=disabled \
        -Dqrencode=disabled \
        -Dgnutls=disabled \
        -Delfutils=disabled \
        -Dpcre2=disabled \
        -Dbzip2=disabled \
        -Dlz4=disabled \
        -Dacl=disabled \
        -Dpwquality=disabled \
        -Dbpf-framework=disabled \
        -Dpasswdqc=disabled \
        \
        `# --- Build-time only ----------------------------------------------` \
        -Dtests=false \
        -Dman=disabled \
        -Dhtml=disabled \
        -Dtranslations=false \
        -Dinstall-tests=false \
        -Dnss-systemd=false \
        -Dnss-mymachines=disabled \
        -Dnss-resolve=disabled \
        -Dukify=disabled \
        -Dsysusers=true \
        -Ddefault-hierarchy=unified \
        -Ddefault-dnssec=no \
        -Dadm-group=false \
        -Dwheel-group=false

    meson compile -C "$BUILDDIR" -j "$JOBS"
    DESTDIR="$DESTDIR" meson install -C "$BUILDDIR" --no-rebuild

    # systemd installs init, halt, poweroff, reboot and shutdown into
    # /usr/sbin. The first of those is what the kernel execs as PID 1, via
    # /sbin/init, so where it lands is not a cosmetic question.
    trinix_merge_usr
}

trinix_check() {
    local missing=''
    # PID 1 and the pieces the rest of Phase 2 depends on. `init` is in the
    # list because the kernel execs /sbin/init and nothing else would notice
    # its absence until the machine panicked.
    for required in usr/lib/systemd/systemd \
                    usr/bin/init \
                    usr/bin/systemctl \
                    usr/bin/journalctl \
                    usr/lib/systemd/systemd-journald \
                    usr/lib/systemd/systemd-udevd; do
        [ -e "$DESTDIR/$required" ] || missing="$missing $required"
    done
    [ -z "$missing" ] || { echo "systemd: missing$missing" >&2; return 1; }

    # systemd-boot is how the A/B image model flips slots, so its absence
    # matters even though nothing boots from it yet.
    ls "$DESTDIR"/usr/lib/systemd/boot/efi/systemd-boot*.efi >/dev/null 2>&1 \
        || { echo 'systemd: systemd-boot EFI binary was not built' >&2; return 1; }
}
