namespace Trinix.Sdk.Generators;

/// <summary>
///     Writes the accessor, the editor and the runtime schema for one
///     <c>[SettingsSchema]</c> interface.
/// </summary>
/// <remarks>
///     <para>
///         Three things come out of one declaration, and each exists because the alternative
///         is a class of bug rather than a keystroke.
///     </para>
///     <list type="bullet">
///         <item><description>
///             <c>Schema</c> — the runtime declaration the store registers, so that the
///             database's own foreign key and kind trigger have something to check against.
///             ⚠ It is built in a static initialiser from constants, with no reflection over
///             the interface: <c>Trinix.Settings</c> builds with the trim and AOT analysers
///             on, and a settings binding that enumerated properties at startup would fail
///             the first <c>PublishAot</c> — in the compositor's build, not in the SDK's.
///         </description></item>
///         <item><description>
///             <c>Keys</c> — one member per key, which is the only spelling of that key in
///             the program. This is the point of the generator: a mistyped key in a string
///             API is not an error anywhere, it is a preference that reads its default
///             forever in a build that passes.
///         </description></item>
///         <item><description>
///             <c>Edit</c> — chaining setters over one <c>SettingsTransaction</c>. Doc 02
///             asks for an atomic multi-key write; emitting it as the <i>shortest</i> way to
///             write anything is how the API makes that easy to obey rather than merely
///             possible.
///         </description></item>
///     </list>
///     <para>
///         ⚠ An enum reads back through a generated <c>switch</c> that falls back to the
///         declared default rather than throwing. That asymmetry with the setter — which
///         does throw on an undefined value — is deliberate: the value going in comes from
///         this program and a bad one is a bug here, while the value coming out comes from a
///         file that a person with <c>sqlite3</c> and a serial console may have edited, and
///         a desktop that will not start because a preference says <c>Darkk</c> is worse
///         than one that is light.
///     </para>
/// </remarks>
static class SettingsEmitter {
    const string Settings = "global::Trinix.Settings";

    /// <summary>Emit the one file this schema produces.</summary>
    /// <param name="contract">The resolved schema.</param>
    public static string Emit(SettingsContract contract) {
        var code = new CodeWriter();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line("#pragma warning disable CS1591 // generated members carry their reason on the declaration");
        code.Line();

        if (contract.Namespace.Length > 0) {
            code.Line($"namespace {contract.Namespace};");
            code.Line();
        }

        code.Line("/// <summary>");
        code.Line($"///     The <c>{contract.Id}</c> settings, as declared by <see cref=\"{contract.InterfaceName}\" />.");
        code.Line("/// </summary>");
        code.Line("/// <remarks>");
        code.Line("///     Generated by Trinix.Sdk.Generators. Reads resolve through every settings layer;");
        code.Line("///     writes go through <see cref=\"BeginEdit\" />, which is one transaction.");
        code.Line("/// </remarks>");
        code.OpenBrace($"{contract.Accessibility} sealed class {contract.AccessorName}");

        EmitSchema(code, contract);
        EmitKeys(code, contract);
        EmitConstruction(code, contract);
        EmitReaders(code, contract);
        EmitSubscription(code, contract);
        EmitEditor(code, contract);
        EmitEnumHelpers(code, contract);

        code.CloseBrace();
        return code.ToString();
    }

    static void EmitSchema(CodeWriter code, SettingsContract contract) {
        code.Line("/// <summary>The schema identifier, which namespaces every key below.</summary>");
        code.Line($"public const string SchemaId = \"{contract.Id}\";");
        code.Line();

        code.Line("/// <summary>The declaration this schema registers with a store.</summary>");
        code.Line($"public static {Settings}.SettingsSchema Schema {{ get; }} = new {Settings}.SettingsSchema(");
        code.Indent();
        code.Line("SchemaId,");
        code.OpenBrace($"new {Settings}.SettingDescriptor[]");

        foreach (var member in contract.Members) {
            code.Line($"new {Settings}.SettingDescriptor(");
            code.Indent();
            code.Line($"\"{member.Name}\",");
            code.Line($"{member.DefaultValueExpression},");
            code.Line($"{Quote(member.Summary)}");
            code.Outdent();
            code.Line("),");
        }

        code.CloseBrace();
        code.Outdent();
        code.Line(");");
        code.Line();
    }

    static void EmitKeys(CodeWriter code, SettingsContract contract) {
        code.Line("/// <summary>Every key in this schema. The only spelling of them in the program.</summary>");
        code.OpenBrace("public static class Keys");

        foreach (var member in contract.Members) {
            code.Line($"/// <summary>{Escape(member.Summary)}</summary>");
            code.Line(
                $"public static {Settings}.SettingsKey {member.Name} => "
                + $"new {Settings}.SettingsKey(SchemaId, \"{member.Name}\");"
            );
        }

        code.CloseBrace();
        code.Line();
    }

    static void EmitConstruction(CodeWriter code, SettingsContract contract) {
        code.Line($"readonly {Settings}.SettingsStore _store;");
        code.Line();
        code.Line("/// <summary>Read and write this schema's keys in a store.</summary>");
        code.Line("/// <param name=\"store\">The store. The schema is registered with it here.</param>");
        code.OpenBrace($"public {contract.AccessorName}({Settings}.SettingsStore store)");
        code.Line("_store = store ?? throw new global::System.ArgumentNullException(nameof(store));");
        code.Line("// Registering in the constructor rather than asking the caller to: a store that");
        code.Line("// has not been told about a schema refuses every key in it, and \"you forgot to");
        code.Line("// register\" is not a diagnosis anybody should have to make twice.");
        code.Line("_store.Register(Schema);");
        code.CloseBrace();
        code.Line();
        code.Line("/// <summary>The store these settings live in.</summary>");
        code.Line($"public {Settings}.SettingsStore Store => _store;");
        code.Line();
    }

    static void EmitReaders(CodeWriter code, SettingsContract contract) {
        foreach (var member in contract.Members) {
            code.Line($"/// <summary>{Escape(member.Summary)}</summary>");
            code.Line($"public {member.PropertyType} {member.Name} => {Read(member)};");
            code.Line();

            code.Line($"/// <summary>Where <see cref=\"{member.Name}\" />'s value came from.</summary>");
            code.Line(
                $"public {Settings}.SettingsResolution Resolve{member.Name}() => _store.Resolve(Keys.{member.Name});"
            );
            code.Line();
        }
    }

    static void EmitSubscription(CodeWriter code, SettingsContract contract) {
        code.Line("/// <summary>");
        code.Line("///     Be told when any key in this schema changes.");
        code.Line("/// </summary>");
        code.Line("/// <remarks>");
        code.Line("///     Doc 02: an application that wants to follow the accent colour subscribes. The");
        code.Line("///     handler is called once per commit that moved something in this schema, never");
        code.Line("///     once per key, and is handed this accessor so that it re-reads rather than being");
        code.Line("///     given a value that is already one commit stale.");
        code.Line("/// </remarks>");
        code.Line("/// <param name=\"handler\">Called after each commit that changed something here.</param>");
        code.Line("/// <returns>Dispose to stop listening.</returns>");
        code.OpenBrace(
            $"public global::System.IDisposable Subscribe(global::System.Action<{contract.AccessorName}> handler)"
        );
        code.Line("if (handler is null) { throw new global::System.ArgumentNullException(nameof(handler)); }");
        code.Line();
        code.Line($"global::System.EventHandler<{Settings}.SettingsChangedEventArgs> onChanged =");
        code.Indent();
        code.Line("(sender, args) => { if (args.Touches(SchemaId)) { handler(this); } };");
        code.Outdent();
        code.Line("_store.Changed += onChanged;");
        code.Line("return new Subscription(_store, onChanged);");
        code.CloseBrace();
        code.Line();

        code.OpenBrace("sealed class Subscription : global::System.IDisposable");
        code.Line($"{Settings}.SettingsStore? _subscribed;");
        code.Line($"readonly global::System.EventHandler<{Settings}.SettingsChangedEventArgs> _handler;");
        code.Line();
        code.OpenBrace(
            $"public Subscription({Settings}.SettingsStore store, "
            + $"global::System.EventHandler<{Settings}.SettingsChangedEventArgs> handler)"
        );
        code.Line("_subscribed = store;");
        code.Line("_handler = handler;");
        code.CloseBrace();
        code.Line();
        code.OpenBrace("public void Dispose()");
        code.Line("// Idempotent, and it has to be: a pane that disposes twice is a pane that would");
        code.Line("// otherwise remove somebody else's handler on the second call.");
        code.Line("var store = _subscribed;");
        code.Line("_subscribed = null;");
        code.Line("if (store is not null) { store.Changed -= _handler; }");
        code.CloseBrace();
        code.CloseBrace();
        code.Line();
    }

    static void EmitEditor(CodeWriter code, SettingsContract contract) {
        code.Line("/// <summary>Begin a change to this schema. Every setter chains into one transaction.</summary>");
        code.Line("public Edit BeginEdit() => new Edit(_store.BeginWrite());");
        code.Line();

        code.Line("/// <summary>");
        code.Line("///     A set of changes to this schema that happen together or not at all.");
        code.Line("/// </summary>");
        code.Line("/// <remarks>");
        code.Line("///     Nothing is written until <see cref=\"Commit\" />, and nothing is locked before it.");
        code.Line("/// </remarks>");
        code.OpenBrace("public sealed class Edit");
        code.Line($"readonly {Settings}.SettingsTransaction _transaction;");
        code.Line();
        code.OpenBrace($"internal Edit({Settings}.SettingsTransaction transaction)");
        code.Line("_transaction = transaction;");
        code.CloseBrace();
        code.Line();

        foreach (var member in contract.Members) {
            code.Line($"/// <summary>Set: {Escape(member.Summary)}</summary>");
            code.OpenBrace($"public Edit Set{member.Name}({member.PropertyType} value)");
            code.Line($"_transaction.Set(Keys.{member.Name}, {Write(member)});");
            code.Line("return this;");
            code.CloseBrace();
            code.Line();

            code.Line($"/// <summary>Drop this layer's value for <c>{member.Name}</c>, falling back to the one below.</summary>");
            code.OpenBrace($"public Edit Reset{member.Name}()");
            code.Line($"_transaction.Reset(Keys.{member.Name});");
            code.Line("return this;");
            code.CloseBrace();
            code.Line();
        }

        code.Line("/// <summary>Drop this layer's value for every key in the schema — doc 08's \"reset this pane\".</summary>");
        code.OpenBrace("public Edit ResetAll()");
        foreach (var member in contract.Members) {
            code.Line($"_transaction.Reset(Keys.{member.Name});");
        }

        code.Line("return this;");
        code.CloseBrace();
        code.Line();

        code.Line("/// <summary>Apply every change at once, and notify once.</summary>");
        code.Line("public void Commit() => _transaction.Commit();");
        code.CloseBrace();
        code.Line();
    }

    static void EmitEnumHelpers(CodeWriter code, SettingsContract contract) {
        foreach (var member in contract.Members) {
            if (member.EnumMembers is not { } names) {
                continue;
            }

            code.Line($"static {member.PropertyType} Parse{member.Name}(string member) => member switch");
            code.OpenBrace("");
            foreach (var name in names) {
                code.Line($"\"{name}\" => {member.PropertyType}.{name},");
            }

            code.Line("// A member this build does not know: an older database, or a hand edit. The");
            code.Line("// declared default is the only answer that keeps a desktop starting.");
            code.Line($"_ => {member.DefaultLiteral},");
            code.CloseBrace(";");
            code.Line();

            code.Line($"static string NameOf{member.Name}({member.PropertyType} value) => value switch");
            code.OpenBrace("");
            foreach (var name in names) {
                code.Line($"{member.PropertyType}.{name} => \"{name}\",");
            }

            code.Line("// Unlike the reader, this throws: the value came from this program, so an");
            code.Line("// undefined one is a cast from an int somewhere and storing its number would");
            code.Line("// put a value in the database that no build can name.");
            code.Line("_ => throw new global::System.ArgumentOutOfRangeException(");
            code.Indent();
            // Without the global:: — this string is read by a person in a log, not by a compiler.
            code.Line($"nameof(value), value, \"Not a member of {member.PropertyType.Replace("global::", "")}.\"),");
            code.Outdent();
            code.CloseBrace(";");
            code.Line();
        }
    }

    static string Read(SettingsMember member) => member.Kind switch {
        "Bool" => $"_store.Get(Keys.{member.Name}).AsBool()",
        "Integer" when member.PropertyType == "int" => $"(int)_store.Get(Keys.{member.Name}).AsInteger()",
        "Integer" => $"_store.Get(Keys.{member.Name}).AsInteger()",
        "Real" => $"_store.Get(Keys.{member.Name}).AsReal()",
        "Text" => $"_store.Get(Keys.{member.Name}).AsText()",
        _ => $"Parse{member.Name}(_store.Get(Keys.{member.Name}).AsEnumMember())",
    };

    static string Write(SettingsMember member) => member.Kind switch {
        "Bool" => $"{Settings}.SettingValue.Bool(value)",
        "Integer" => $"{Settings}.SettingValue.Integer(value)",
        "Real" => $"{Settings}.SettingValue.Real(value)",
        "Text" => $"{Settings}.SettingValue.Text(value)",
        _ => $"{Settings}.SettingValue.EnumMember(NameOf{member.Name}(value))",
    };

    // The summary reaches generated source twice: once as a C# string literal for the
    // descriptor, and once inside an XML doc comment. Two escapings, and mixing them up
    // produces source that compiles and documentation that lies.
    static string Quote(string text) => "\"" + text
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", "\\r")
        .Replace("\n", "\\n") + "\"";

    static string Escape(string text) => text
        .Replace("&", "&amp;")
        .Replace("<", "&lt;")
        .Replace(">", "&gt;")
        .Replace("\r", " ")
        .Replace("\n", " ");
}
