using System.Collections.Generic;

namespace Trinix.Sdk.Generators;

/// <summary>
///     Emits the one class that knows how every <c>[ServiceRecord]</c> in an assembly is
///     laid out on the wire.
/// </summary>
/// <remarks>
///     <para>
///         One class per assembly rather than one per service, because a record used by
///         three services should marshal through one piece of code. The generated proxies
///         and handlers reach it with a <c>using static</c>, so the call sites read
///         <c>WriteNotificationRequest(ref writer, request)</c> and nothing has to know
///         where it lives.
///     </para>
///     <para>
///         ⚠ Every method here is <c>static</c> and takes its writer or reader
///         <c>ref</c>. That is not a performance choice — <c>MessageWriter</c> and
///         <c>Reader</c> are <c>ref struct</c>s and cannot be captured, boxed, or held by
///         anything with a state machine. Passing by <c>ref</c> is the only way a nested
///         record's members can be written into the same message as its parent's.
///     </para>
/// </remarks>
static class WireEmitter {
    /// <summary>Emit the marshalling helpers for every record in one assembly.</summary>
    /// <param name="records">The resolved records.</param>
    /// <param name="wireClass">The fully-qualified name to emit, namespace included.</param>
    public static string Emit(IReadOnlyList<RecordWire> records, string wireClass) {
        var separator = wireClass.LastIndexOf('.');
        var wireNamespace = wireClass.Substring(0, separator);
        var wireName = wireClass.Substring(separator + 1);

        var code = new CodeWriter();
        code.Line("// <auto-generated/>");
        code.Line("#nullable enable");
        code.Line("#pragma warning disable CS1591");
        code.Line();
        code.Line($"namespace {wireNamespace};");
        code.Line();
        code.Line("/// <summary>How this assembly's <c>[ServiceRecord]</c> types are laid out on the bus.</summary>");
        code.Line("/// <remarks>");
        code.Line("///     ⚠ Generated. The member order below <b>is</b> the wire format: it comes from each");
        code.Line("///     record's primary constructor, so reordering the parameters of a record changes");
        code.Line("///     what a peer built against the old order decodes, without changing its signature");
        code.Line("///     and therefore without anything failing.");
        code.Line("/// </remarks>");
        code.Line("[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]");
        code.OpenBrace($"public static class {wireName}");

        foreach (var record in records) {
            code.Line($"/// <summary>The D-Bus signature of <c>{record.Name}</c>: <c>{record.Signature}</c>.</summary>");
            code.Line($"public const string {record.Name}Signature = \"{record.Signature}\";");
            code.Line();

            code.OpenBrace(
                $"public static void Write{record.Name}(ref global::Tmds.DBus.Protocol.MessageWriter writer, "
                + $"{record.CSharpType} value)"
            );
            record.EmitWriterBody(code);
            code.CloseBrace();
            code.Line();

            code.OpenBrace(
                $"public static {record.CSharpType} Read{record.Name}(ref global::Tmds.DBus.Protocol.Reader reader)"
            );
            record.EmitReaderBody(code);
            code.CloseBrace();
            code.Line();
        }

        code.CloseBrace();
        return code.ToString();
    }
}
