/*
 * trinix-wl-demo — a Wayland client that reports what happened to it.
 *
 * Phase 4's exit criterion is that a client runs windowed under Trinix's
 * compositor. Proving that inside a VM with no screen means the proof has to
 * be textual, and this is a client written to produce it: it binds the globals
 * a real application binds, creates an xdg_toplevel, waits for the configure
 * the compositor is obliged to send, paints a shared-memory buffer, and counts
 * the frame callbacks that come back. Every step prints a line, so a boot check
 * reading a serial console can tell which one failed.
 *
 * It uses nothing but libwayland and the xdg-shell protocol from
 * wayland-protocols, generated by the same pinned wayland-scanner every other
 * Wayland component in the image was built with — so what it exercises is the
 * protocol, not a private arrangement with the compositor. The compositor
 * knows nothing about it.
 */
#define _GNU_SOURCE

#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>

#include <wayland-client.h>
#include <xkbcommon/xkbcommon-keysyms.h>

#include "trinix-menu-v1-client-protocol.h"
#include "trinix-shell-v1-client-protocol.h"
#include "xdg-shell-client-protocol.h"

#define DEFAULT_WIDTH 640
#define DEFAULT_HEIGHT 480

/* Every line the check greps for starts with this. */
#define TAG "TRINIX-WL-DEMO"

struct demo {
    struct wl_display *display;
    struct wl_registry *registry;
    struct wl_compositor *compositor;
    struct wl_shm *shm;
    struct xdg_wm_base *wm_base;
    struct wl_seat *seat;
    struct trinix_shell_v1 *shell;
    struct trinix_menu_manager_v1 *menu_manager;

    struct wl_surface *surface;
    struct xdg_surface *xdg_surface;
    struct xdg_toplevel *toplevel;
    struct trinix_shell_surface_v1 *shell_surface;
    struct trinix_menu_v1 *menu;
    struct wl_buffer *buffer;
    void *pixels;
    size_t pixels_size;

    int width;
    int height;
    int frames;
    int frames_wanted;
    bool configured;
    bool closed;
    bool failed;

    /* What came back over the two Trinix extensions, so the check can assert
     * the round trip rather than merely that nothing crashed. */
    uint32_t shell_capabilities;
    bool shadow_reported;
    int32_t shadow_left, shadow_top, shadow_right, shadow_bottom;
};

static void registry_global(void *data, struct wl_registry *registry, uint32_t name,
                            const char *interface, uint32_t version) {
    struct demo *demo = data;
    (void)version;

    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        demo->compositor = wl_registry_bind(registry, name, &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        demo->shm = wl_registry_bind(registry, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, xdg_wm_base_interface.name) == 0) {
        demo->wm_base = wl_registry_bind(registry, name, &xdg_wm_base_interface, 1);
    } else if (strcmp(interface, wl_seat_interface.name) == 0) {
        demo->seat = wl_registry_bind(registry, name, &wl_seat_interface, 1);
    } else if (strcmp(interface, trinix_shell_v1_interface.name) == 0) {
        demo->shell = wl_registry_bind(registry, name, &trinix_shell_v1_interface, 1);
    } else if (strcmp(interface, trinix_menu_manager_v1_interface.name) == 0) {
        demo->menu_manager =
            wl_registry_bind(registry, name, &trinix_menu_manager_v1_interface, 1);
    }
}

static void registry_global_remove(void *data, struct wl_registry *registry, uint32_t name) {
    (void)data;
    (void)registry;
    (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global = registry_global,
    .global_remove = registry_global_remove,
};

/* A compositor that stops answering pings is one a client is entitled to give
 * up on, so answering them is not optional even in a demo. */
static void wm_base_ping(void *data, struct xdg_wm_base *wm_base, uint32_t serial) {
    (void)data;
    xdg_wm_base_pong(wm_base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = {
    .ping = wm_base_ping,
};

/* --- trinix-shell-v1 ---------------------------------------------------- */

static void shell_capabilities(void *data, struct trinix_shell_v1 *shell,
                               uint32_t capabilities) {
    struct demo *demo = data;
    (void)shell;

    demo->shell_capabilities = capabilities;
    printf("%s: shell capabilities shadow=%d rounded=%d blur=%d\n", TAG,
           (capabilities & TRINIX_SHELL_V1_CAPABILITY_SHADOW) != 0,
           (capabilities & TRINIX_SHELL_V1_CAPABILITY_ROUNDED_CORNERS) != 0,
           (capabilities & TRINIX_SHELL_V1_CAPABILITY_BLUR) != 0);
    fflush(stdout);
}

static const struct trinix_shell_v1_listener shell_listener = {
    .capabilities = shell_capabilities,
};

static void shell_surface_control_activated(void *data,
                                            struct trinix_shell_surface_v1 *shell_surface,
                                            uint32_t control) {
    struct demo *demo = data;
    (void)shell_surface;

    /* A request, not an instruction — which is exactly why the client is the
     * one that decides to stop. */
    printf("%s: control activated %u\n", TAG, control);
    fflush(stdout);
    if (control == TRINIX_SHELL_SURFACE_V1_CONTROL_CLOSE) {
        demo->closed = true;
    }
}

static void shell_surface_control_hover(void *data,
                                        struct trinix_shell_surface_v1 *shell_surface,
                                        uint32_t control, uint32_t state) {
    (void)data;
    (void)shell_surface;

    /* A real client would redraw its traffic lights here. */
    printf("%s: control hover %u state %u\n", TAG, control, state);
    fflush(stdout);
}

static void shell_surface_shadow_applied(void *data,
                                         struct trinix_shell_surface_v1 *shell_surface,
                                         int32_t left, int32_t top, int32_t right,
                                         int32_t bottom) {
    struct demo *demo = data;
    (void)shell_surface;

    demo->shadow_reported = true;
    demo->shadow_left = left;
    demo->shadow_top = top;
    demo->shadow_right = right;
    demo->shadow_bottom = bottom;
    printf("%s: shadow margins %d,%d,%d,%d\n", TAG, left, top, right, bottom);
    fflush(stdout);
}

static const struct trinix_shell_surface_v1_listener shell_surface_listener = {
    .control_activated = shell_surface_control_activated,
    .control_hover = shell_surface_control_hover,
    .shadow_applied = shell_surface_shadow_applied,
};

/* --- trinix-menu-v1 ----------------------------------------------------- */

static void menu_activated(void *data, struct trinix_menu_v1 *menu, uint32_t id) {
    (void)data;
    (void)menu;

    printf("%s: menu item %u activated\n", TAG, id);
    fflush(stdout);
}

static void menu_about_to_show(void *data, struct trinix_menu_v1 *menu, uint32_t id) {
    (void)data;

    /* Where an application with an expensive menu would fill it in. This one
     * has nothing to add, and still has to commit so the shell stops waiting. */
    printf("%s: menu %u about to show\n", TAG, id);
    fflush(stdout);
    trinix_menu_v1_commit(menu);
}

static void menu_closed(void *data, struct trinix_menu_v1 *menu) {
    (void)data;
    (void)menu;

    printf("%s: menu closed\n", TAG);
    fflush(stdout);
}

static const struct trinix_menu_v1_listener menu_listener = {
    .activated = menu_activated,
    .about_to_show = menu_about_to_show,
    .closed = menu_closed,
};

/*
 * The decorations this client claims to have drawn.
 *
 * It does not actually draw traffic lights — it has no font and no icons — but
 * it declares them exactly where a real title bar would put them, which is
 * what the protocol is being exercised for. The compositor hit-tests what it
 * is told, not what is painted.
 */
#define TITLE_BAR_HEIGHT 28
#define CONTROL_SIZE 14
#define CONTROL_SPACING 20
#define CONTROL_ORIGIN 12

static void declare_decorations(struct demo *demo) {
    if (demo->shell == NULL) {
        return;
    }

    demo->shell_surface = trinix_shell_v1_get_shell_surface(demo->shell, demo->toplevel);
    trinix_shell_surface_v1_add_listener(demo->shell_surface, &shell_surface_listener, demo);

    trinix_shell_surface_v1_set_shadow(demo->shell_surface,
                                       TRINIX_SHELL_SURFACE_V1_SHADOW_STYLE_WINDOW);
    trinix_shell_surface_v1_set_corner_radius(demo->shell_surface, 10);
    trinix_shell_surface_v1_set_resize_inset(demo->shell_surface, 4);

    for (uint32_t control = 0; control < 3; control++) {
        trinix_shell_surface_v1_set_control(
            demo->shell_surface, control,
            CONTROL_ORIGIN + (int32_t)(control * CONTROL_SPACING),
            (TITLE_BAR_HEIGHT - CONTROL_SIZE) / 2, CONTROL_SIZE, CONTROL_SIZE);
    }

    /* The title bar, minus the controls: dragging here moves the window, and
     * the client never hears about the motion. */
    struct wl_region *drag = wl_compositor_create_region(demo->compositor);
    wl_region_add(drag, CONTROL_ORIGIN + (3 * CONTROL_SPACING), 0,
                  demo->width - CONTROL_ORIGIN - (3 * CONTROL_SPACING), TITLE_BAR_HEIGHT);
    trinix_shell_surface_v1_set_drag_region(demo->shell_surface, drag);
    wl_region_destroy(drag);
}

/*
 * A menu bar, described rather than drawn. Two menus, a submenu, a separator,
 * a checkbox and an accelerator — enough that anything which mishandles the
 * tree or the ordering shows up in what the shell reports back.
 */
static void export_menu(struct demo *demo) {
    if (demo->menu_manager == NULL) {
        return;
    }

    demo->menu = trinix_menu_manager_v1_get_menu_bar(demo->menu_manager, demo->toplevel);
    trinix_menu_v1_add_listener(demo->menu, &menu_listener, demo);

    trinix_menu_v1_insert(demo->menu, 1, 0, -1, TRINIX_MENU_V1_KIND_SUBMENU, "_File");
    trinix_menu_v1_insert(demo->menu, 2, 1, -1, TRINIX_MENU_V1_KIND_ITEM, "_New Window");
    /* Command-N, handled by the shell whether or not the menu is ever opened. */
    trinix_menu_v1_set_accelerator(demo->menu, 2, XKB_KEY_n, TRINIX_MENU_V1_MODIFIER_LOGO);
    trinix_menu_v1_insert(demo->menu, 3, 1, -1, TRINIX_MENU_V1_KIND_SEPARATOR, "");
    trinix_menu_v1_insert(demo->menu, 4, 1, -1, TRINIX_MENU_V1_KIND_ITEM, "_Close");
    trinix_menu_v1_set_accelerator(demo->menu, 4, XKB_KEY_w, TRINIX_MENU_V1_MODIFIER_LOGO);

    trinix_menu_v1_insert(demo->menu, 5, 0, -1, TRINIX_MENU_V1_KIND_SUBMENU, "_View");
    trinix_menu_v1_insert(demo->menu, 6, 5, -1, TRINIX_MENU_V1_KIND_CHECKBOX, "_Show Grid");
    trinix_menu_v1_update(demo->menu, 6, "_Show Grid",
                          TRINIX_MENU_V1_STATE_ENABLED | TRINIX_MENU_V1_STATE_CHECKED);

    trinix_menu_v1_commit(demo->menu);
}

/* Anonymous shared memory the compositor can map. memfd rather than a file in
 * /tmp: there is no writable /tmp guarantee this early, and a sealed memfd is
 * what every modern toolkit uses. */
static int create_shm(size_t size, void **out) {
    int fd = memfd_create("trinix-wl-demo", MFD_CLOEXEC | MFD_ALLOW_SEALING);
    if (fd < 0) {
        return -1;
    }
    if (ftruncate(fd, (off_t)size) < 0) {
        close(fd);
        return -1;
    }

    void *pixels = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (pixels == MAP_FAILED) {
        close(fd);
        return -1;
    }

    *out = pixels;
    return fd;
}

/*
 * Something recognisably rendered rather than a flat fill: a gradient with a
 * border, so that a screenshot — once there is a way to take one — shows
 * whether the buffer arrived intact and the right way up.
 */
static void paint(struct demo *demo, int tick) {
    uint32_t *row = demo->pixels;

    for (int y = 0; y < demo->height; y++) {
        for (int x = 0; x < demo->width; x++) {
            bool border = x < 3 || y < 3 || x >= demo->width - 3 || y >= demo->height - 3;
            uint32_t red = border ? 0xff : (uint32_t)((x * 255) / demo->width);
            uint32_t green = border ? 0x60 : (uint32_t)((y * 255) / demo->height);
            uint32_t blue = border ? 0x20 : (uint32_t)((tick * 8) & 0xff);
            row[(y * demo->width) + x] = 0xff000000u | (red << 16) | (green << 8) | blue;
        }
    }
}

static bool allocate_buffer(struct demo *demo) {
    size_t stride = (size_t)demo->width * 4;
    size_t size = stride * (size_t)demo->height;

    int fd = create_shm(size, &demo->pixels);
    if (fd < 0) {
        fprintf(stderr, "%s: shared memory failed: %s\n", TAG, strerror(errno));
        return false;
    }
    demo->pixels_size = size;

    struct wl_shm_pool *pool = wl_shm_create_pool(demo->shm, fd, (int32_t)size);
    demo->buffer = wl_shm_pool_create_buffer(pool, 0, demo->width, demo->height,
                                             (int32_t)stride, WL_SHM_FORMAT_ARGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);

    return demo->buffer != NULL;
}

static const struct wl_callback_listener frame_listener;

static void frame_done(void *data, struct wl_callback *callback, uint32_t time) {
    struct demo *demo = data;
    (void)time;

    wl_callback_destroy(callback);
    demo->frames++;

    if (demo->frames >= demo->frames_wanted) {
        return;
    }

    paint(demo, demo->frames);
    struct wl_callback *next = wl_surface_frame(demo->surface);
    wl_callback_add_listener(next, &frame_listener, demo);
    wl_surface_attach(demo->surface, demo->buffer, 0, 0);
    wl_surface_damage_buffer(demo->surface, 0, 0, demo->width, demo->height);
    wl_surface_commit(demo->surface);
}

static const struct wl_callback_listener frame_listener = {
    .done = frame_done,
};

static void xdg_surface_configure(void *data, struct xdg_surface *xdg_surface, uint32_t serial) {
    struct demo *demo = data;

    xdg_surface_ack_configure(xdg_surface, serial);

    if (demo->configured) {
        return;
    }
    demo->configured = true;
    printf("%s: configured %dx%d\n", TAG, demo->width, demo->height);
    fflush(stdout);

    if (!allocate_buffer(demo)) {
        demo->failed = true;
        return;
    }

    paint(demo, 0);
    struct wl_callback *callback = wl_surface_frame(demo->surface);
    wl_callback_add_listener(callback, &frame_listener, demo);
    wl_surface_attach(demo->surface, demo->buffer, 0, 0);
    wl_surface_damage_buffer(demo->surface, 0, 0, demo->width, demo->height);
    wl_surface_commit(demo->surface);
}

static const struct xdg_surface_listener xdg_surface_listener = {
    .configure = xdg_surface_configure,
};

static void toplevel_configure(void *data, struct xdg_toplevel *toplevel,
                               int32_t width, int32_t height, struct wl_array *states) {
    struct demo *demo = data;
    (void)toplevel;
    (void)states;

    /* Zero means "you choose", which is what Trinix's compositor says. */
    if (width > 0 && height > 0 && !demo->configured) {
        demo->width = width;
        demo->height = height;
    }
}

static void toplevel_close(void *data, struct xdg_toplevel *toplevel) {
    struct demo *demo = data;
    (void)toplevel;

    printf("%s: close requested\n", TAG);
    fflush(stdout);
    demo->closed = true;
}

static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = toplevel_configure,
    .close = toplevel_close,
};

int main(int argc, char *argv[]) {
    struct demo demo = {
        .width = DEFAULT_WIDTH,
        .height = DEFAULT_HEIGHT,
        .frames_wanted = 10,
    };

    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "--frames") == 0 && i + 1 < argc) {
            demo.frames_wanted = atoi(argv[++i]);
        } else {
            fprintf(stderr, "usage: %s [--frames N]\n", argv[0]);
            return 2;
        }
    }

    demo.display = wl_display_connect(NULL);
    if (demo.display == NULL) {
        fprintf(stderr, "%s: no compositor on WAYLAND_DISPLAY\n", TAG);
        return 1;
    }
    printf("%s: connected to %s\n", TAG,
           getenv("WAYLAND_DISPLAY") ? getenv("WAYLAND_DISPLAY") : "(default)");

    demo.registry = wl_display_get_registry(demo.display);
    wl_registry_add_listener(demo.registry, &registry_listener, &demo);
    wl_display_roundtrip(demo.display);

    printf("%s: globals compositor=%d shm=%d xdg_wm_base=%d seat=%d\n", TAG,
           demo.compositor != NULL, demo.shm != NULL, demo.wm_base != NULL, demo.seat != NULL);
    printf("%s: trinix globals shell=%d menu=%d\n", TAG,
           demo.shell != NULL, demo.menu_manager != NULL);
    fflush(stdout);

    if (demo.compositor == NULL || demo.shm == NULL || demo.wm_base == NULL) {
        fprintf(stderr, "%s: compositor is missing a required global\n", TAG);
        return 1;
    }
    xdg_wm_base_add_listener(demo.wm_base, &wm_base_listener, &demo);
    if (demo.shell != NULL) {
        trinix_shell_v1_add_listener(demo.shell, &shell_listener, &demo);
    }

    demo.surface = wl_compositor_create_surface(demo.compositor);
    demo.xdg_surface = xdg_wm_base_get_xdg_surface(demo.wm_base, demo.surface);
    xdg_surface_add_listener(demo.xdg_surface, &xdg_surface_listener, &demo);
    demo.toplevel = xdg_surface_get_toplevel(demo.xdg_surface);
    xdg_toplevel_add_listener(demo.toplevel, &toplevel_listener, &demo);
    xdg_toplevel_set_title(demo.toplevel, "Trinix Wayland demo");
    xdg_toplevel_set_app_id(demo.toplevel, "io.trinix.WaylandDemo");

    /* The two Trinix extensions, exercised the way an application would: the
     * decorations this client claims to have drawn, and the menus it wants the
     * shell to draw for it. Both are optional — a compositor without them is
     * still a compositor, and this client still runs. */
    declare_decorations(&demo);
    export_menu(&demo);

    /* The first commit carries no buffer: it asks for the configure that the
     * protocol requires before a buffer may be attached at all. */
    wl_surface_commit(demo.surface);

    while (!demo.closed && !demo.failed && demo.frames < demo.frames_wanted) {
        if (wl_display_dispatch(demo.display) < 0) {
            fprintf(stderr, "%s: connection lost\n", TAG);
            demo.failed = true;
            break;
        }
    }

    bool ok = !demo.failed && demo.configured && demo.frames >= demo.frames_wanted;
    printf("%s: frames=%d\n", TAG, demo.frames);

    /* The extensions are optional, so their absence is reported and does not
     * fail the run — but if they were present, the round trip has to have
     * completed, because a protocol that binds and then says nothing is worse
     * than one that is missing. */
    if (demo.shell != NULL) {
        if (!demo.shadow_reported) {
            fprintf(stderr, "%s: the shell never reported shadow margins\n", TAG);
            ok = false;
        }
        printf("%s: shell round trip capabilities=0x%x shadow=%d\n", TAG,
               demo.shell_capabilities, demo.shadow_reported);
    }
    if (demo.menu != NULL) {
        printf("%s: menu exported\n", TAG);
    }
    printf("%s-%s\n", TAG, ok ? "OK" : "FAILED");
    fflush(stdout);

    if (demo.pixels != NULL) {
        munmap(demo.pixels, demo.pixels_size);
    }
    wl_display_disconnect(demo.display);
    return ok ? 0 : 1;
}
